version: 0.2
env:
  variables:
    STACK_NAME: food-decider
    REGION: us-west-2
phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - npm install -g serverless@3
      - npm install
      - pip install --upgrade pip
      - pip install numpy --upgrade
      - apt-get update
      - apt-get -y install jq
      - parseStackOutput=${CODEBUILD_SRC_DIR}/buildspecs/helpers/parse-stack-outputs.sh
      - parseStackOutputAuth=${CODEBUILD_SRC_DIR}/buildspecs/helpers/parse-stack-outputs-auth.sh
      - chmod +x $parseStackOutput
      - chmod +x $parseStackOutputAuth
  build:
    commands:
      - echo "----- Running Build ------"
      - cd ${CODEBUILD_SRC_DIR}
      - npx serverless deploy --stage ${CURRENT_STAGE} --region ${REGION}
      - aws cloudformation describe-stacks --stack-name ${STACK_NAME}-${CURRENT_STAGE} > ${CODEBUILD_SRC_DIR}/stack-outputs.json
