Resources:
# *********************************************************** DynamoDB ***********************************************************
  FoodOptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${self:provider.stage}-food-options
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
        - AttributeName: food_type
          AttributeType: S
        - AttributeName: visited
          AttributeType: B        
      KeySchema:
        - AttributeName: name
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: food_type-index
          KeySchema:
            - AttributeName: food_type
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: visited-index
          KeySchema:
            - AttributeName: visited
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true